Making the build process friendlier

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -2,6 +2,42 @@
 git submodule init
 git submodule update --init --recursive --remote
 
+# Cleanup
 sed -i "s/\\r//g" server/bin/combine
+cd gui
+if ! npm run clean &>/dev/null; then
+    
+    complete=false;
 
+    while ! $complete; do
+
+        read -p "Could not remove previous build's intermediate files.  Try again as administrator? (Y/n)" response;
+        response=$(echo "$response" | awk '{print tolower($0)}');
+
+        if [ "$response" == "y" ] || [ "$response" == "" ]; then
+            sudo npm run clean;
+            complete=true;
+        elif [ "$response" == "n" ]; then
+            exit 1;
+        else
+            echo "Invalid response $response";
+        fi;
+
+    done;
+
+fi;
+
+cd ../
 docker-compose build
+
+# Install npm dependencies for the gui
+cd gui
+container=$(docker run -itd -v $(pwd):/app topazdb/gui);
+uid=$(id -u);
+
+docker exec $container npm i && npm run build
+docker exec $container chown -R $uid node_modules dist # allow developers to use npm client outside of docker
+
+echo "Cleaning up..."
+docker stop $container >/dev/null && docker rm $container >/dev/null
+echo "Done"
